language: php

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.4
      name: PHPStan
      script:
        - vendor/bin/phpstan analyse --no-progress

install:
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text
